server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

eureka:
  client:
    service-url:
      defaultZone: localhost:8761/eureka

spring:
  datasource:
    username: userService
    password: userService
    url: jdbc:postgresql://localhost:5432/user_service
  mail:
    host: smtp.yandex.ru
    port: 465
    protocol: smtps
    username: uparse.confirmation@yandex.ru
    password: jcfwyjrsjuobgqth
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
        ssl:
          enable: true
        sender:
          email: uparse.confirmation@yandex.ru

jwt:
  jwtSecret: CzBWQs4W2SoUHFDjVUWPEP3rSUGCO9afPcYh8oYWqk0ht2XN3auyJYYdzcnXV0lq
  jwtExpirationMs: 7200000

mail-service:
  activation:
    uri: http://localhost:8080/api/auth/activation?id={id}
  crypto-util:
    salt: Pq12GSnZ5CwkrmutojxQbMl3cRi8speFya760ONUYKgThHAWJIfLdD9V4XEvzB