server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: parserDataBase
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    properties:
      hibernate:
      format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  mail:
    host: smtp.yandex.ru
    port: 8085
    protocol: smtps
    username: uparse.confirmation@yandex.ru
    password: 1234567890ABC
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: adminPassword

# noinspection undefined
webdriver:
  http:
    factory: jdk-http-client
  chrome:
    driver: src/main/resources/driver/chrome/chromedriver_macOS
  #    For Windows (32)
  # webdriver.chrome.driver=src/main/resources/driver/chrome/chromedriver_windows32.exe
  #    For Linux (64)
  # webdriver.chrome.driver=src/main/resources/driver/chrome/chromedriver_linux64

# noinspection undefined
researchser:
  jwtSecret: CzBWQs4W2SoUHFDjVUWPEP3rSUGCO9afPcYh8oYWqk0ht2XN3auyJYYdzcnXV0lq
  jwtExpirationMs: 86400000

# noinspection undefined
service:
  activation:
    uri: http://localhost:8080/api/auth/activation?id={id}
