server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: user-service
  #  sql:
  #    init:
  #      mode: always
  datasource:
    username: user_service
    password: user_service
    url: jdbc:postgresql://db-postgres:5432/user_service
  mail:
    host: smtp.yandex.ru
    port: 465
    protocol: smtps
    username: uparse.confirmation@yandex.ru
    password: jcfwyjrsjuobgqth
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
        ssl:
          enable: true
        sender:
          email: uparse.confirmation@yandex.ru

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.type.descriptor.sql: TRACE

management:
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,beans
  metrics:
    export:
      loki:
        enabled: true
        step: 1m
    tags:
      application: ${spring.application.name}
    prometheus:
      enabled: true
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  zipkin:
    tracing:
      endpoint: http://${TEMPO_HOST:localhost}:${TEMPO_PORT:9411}/api/v2/spans

jwt:
  jwtSecret: CzBWQs4W2SoUHFDjVUWPEP3rSUGCO9afPcYh8oYWqk0ht2XN3auyJYYdzcnXV0lq
  jwtExpirationMs: 7200000

mail-service:
  activation:
    uri: http://user-service:8080/api/auth/activation?activationToken={activationToken}
crypto-util:
  pepper: Pq12GSnZ5CwkrmutojxQbMl3cRi8speFya760ONUYKgThHAWJIfLdD9V4XEvzB