server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: parserDataBase
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    properties:
        hibernate:
        format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQL95Dialect
