server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: DBPASS
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop // посмотреть как пофиксить
    show_sql: true
    properties:
        hibernate:
        format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQL95Dialect
